name: Build App
on:
    push:
    workflow_dispatch:

env:
    IMAGE_NAME: email-microservice
    IMAGE_TAG: development

jobs:
    build-docker:
        name: Build with Dockerfile
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and push
                uses: docker/build-push-action@v2
                with:
                    push: false
                    tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                    build-args: |
                        MAVEN_USERNAME=${{ secrets.MAVEN_USERNAME }}
                        MAVEN_PASSWORD=${{ secrets.MAVEN_PASSWORD }}
    build-gradle:
        name: Build with Gradle
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Set up Java
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'
                    cache: "gradle"
                    cache-dependency-path: |
                        build.gradle.kts
                        settings.gradle.kts
                        gradle/libs.versions.toml
            -   name: Build with Gradle
                run: |
                    ./gradlew buildFatJar --no-daemon
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and push
                uses: docker/build-push-action@v2
                with:
                    push: false
                    file: single.Dockerfile
                    tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                    build-args: |
                        MAVEN_USERNAME=${{ secrets.MAVEN_USERNAME }}
                        MAVEN_PASSWORD=${{ secrets.MAVEN_PASSWORD }}